//  TRABAJAR CON UNA LISTA DE RECETAS
 
// mandar recetas al front (con uri)(PELADOS II) {ULTIMA SEMANA}


// AGREGAR FAVORITOS (WEATHER GIRLS) {MIERCOLES}

// AGREGAR COMENTARIOS (GOOGLE) (LINKEADO CON USUARIOS.NOMBRE) {ULTIMA SEMANA }


// ESTRELLAS {MIERCOLES}